### ISSUE TITLE
panic while building

### ISSUE THREAD

**Issue by kovetskiy** [hackstream/zettel#28]
zettel build on a shiny new project produces the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xb0e55f]

goroutine 1 [running]:
main.(*Hub).makeDist(0xc00054db90, 0x0, 0x0)
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/build.go:51 +0x7bf
main.(*Hub).build(0xc00054db90, 0xc00064d040, 0xbfeffd, 0x1)
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/build.go:95 +0x185
main.(*Hub).MustHaveConfig.func1(0xc00064d040, 0x1, 0x1)
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/middleware.go:21 +0x15b
github.com/urfave/cli/v2.(*Command).Run(0xc0002e5200, 0xc00064cf80, 0x0, 0x0)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000602300, 0xd88640, 0xc0001e8cf0, 0xc00012c000, 0x2, 0x2, 0x0, 0x0)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/main.go:95 +0x52f
```

config:
```
description = "Hello World. This is my zettel notebook"
pygmentsstyle = "monokailight"
site_name = "My Zettel"
```

**Comment by kovetskiy** [comment]
Oops, I see. The project is not `go get`-able, I ran `make deps` and `make build`, now I see the following panic:
```
 zettel build

DEBU[2020-12-02T17:03:47+03:00] verbose logging enabled
INFO[2020-12-02T17:03:47+03:00] Starting zettel...🚀
2020/12/02 17:03:47 reading config: zettel.toml
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
main.(*Hub).build(0xc00034c9a0, 0xc0007250c0, 0xbfeffd, 0x1)
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/build.go:176 +0x8cf
main.(*Hub).MustHaveConfig.func1(0xc0007250c0, 0x1, 0x1)
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/middleware.go:21 +0x15b
github.com/urfave/cli/v2.(*Command).Run(0xc000514240, 0xc000725000, 0x0, 0x0)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000580480, 0xd886a0, 0xc0001d6e60, 0xc00000e060, 0x2, 0x2, 0x0, 0x0)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /home/operator/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /home/operator/go/src/github.com/hackstream/zettel/cmd/zettel/main.go:95 +0x52f
```

**Comment by iamd3vil** [comment]
Hi,

I am sorry I didn't respond earlier. I was not active due to some things going on in my life. Seems like the panic happens when there's no `index.md` file. I will fix this.
